### ISSUE TITLE
dataset settings

### ISSUE THREAD

**Issue by wangJK20191** [Wenchao-Du/Neighbor2Neighbor_Pytorch#2]
I‘d like to know that how to setup the 'train' ,'test' and 'gt' in config.yaml. Thank you!

**Comment by Wenchao-Du** [comment]
you should add a dataset.py file to acquire your traindataset (the noisy images) based on your input dataset folder, and update the dataroot in config.yaml, and then you could train it. Good luck.

**Comment by DwyaneLQY** [comment]
> you should add a dataset.py file to acquire your traindataset (the noisy images) based on your input dataset folder, and update the dataroot in config.yaml, and then you could train it. Good luck.

I have some questions about using my custom dataset. can I discuss with you about it? Here is my email account：2018141463112@stu.scu.edu.cn. Looking forward to hear from you! Or you may give me your email. Thx!

**Comment by DwyaneLQY** [comment]
This line makes me confused: gt, noise = inputs['gt'].cuda(gpu), inputs['noise'].cuda(gpu) .
the input should be a tensor with shape of (batch_size, channel, H, W), right? how can I use the key, 'gt' and 'noise'?

**Comment by Wenchao-Du** [comment]
> > you should add a dataset.py file to acquire your traindataset (the noisy images) based on your input dataset folder, and update the dataroot in config.yaml, and then you could train it. Good luck.
> 
> I have some questions about using my custom dataset. can I discuss with you about it? Here is my email account：[2018141463112@stu.scu.edu.cn](mailto:2018141463112@stu.scu.edu.cn). Looking forward to hear from you! Or you may give me your email. Thx!
